version: '3.8'

services:
  diesel-kp-app:
    build: .
    container_name: diesel-kp
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=/data/database.sqlite
    volumes:
      - diesel_data:/data
    restart: unless-stopped

volumes:
  diesel_data:
